[package]
name = "maligned"
version = "0.1.0"
authors = ["Tyler Hawkes <tyler.hawkes@gmail.com>"]
edition = "2018"
description = "A complete memory alignment library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tylerhawkes/maligned" 

[features]
alloc = []
default = ["alloc"]

